### ISSUE TITLE
About the performance of RASVSR

### ISSUE THREAD

**Issue by qtct** [Alioth2000/RASVSR#1]
I find that the number of iterations of weight training for each model provided by the code is different, does this compromise the fairness of the experimental comparison? When I trained RASVSR on general VSR tasks, I found that its performance was not very good, should not be better than basicvsr++.However, the performance of RASVSR in the paper is much higher than that of basicvsr++. I was confused. Thank you for your reply.

**Comment by Alioth2000** [comment]
The weights we provide are those that achieve the highest PSNR during training, not those with the highest number of iterations.
RASVSR is designed primarily for satellite video, and we have not tested its effectiveness on general VSR.
