### ISSUE TITLE
Train Error

### ISSUE THREAD

**Issue by Yu-Wang-0801** [Alioth2000/RASVSR#2]
May I ask if the 53rd line edvr_path: experiments/pretrained_models/edvr_reds_pretrained_new.pth in options/train_IconVSR.yml is a necessary pre-trained model when training the IconVSR model, or how to train this training model? Looking forward to your reply, thank you!

**Comment by Alioth2000** [comment]
The authors of IconVSR used that pre-trained weights for training, which you can get from https://drive.google.com/file/d/1ShfwddugTmT3_kB8VL6KpCMrIpEO5sBi/view?usp=drive_link

**Comment by Yu-Wang-0801** [comment]
![image](https://github.com/user-attachments/assets/76ed3899-aa7e-4544-b761-adf318fc9f6a)
Thank you for your reply! But when I trained EDVR twice, the error shown in the figure appeared. What is the reason or how should I modify the code?

**Comment by Alioth2000** [comment]
You can refer to this answer for this question: https://github.com/Armstrong-lsw/SR_Self_Align/issues/2#issuecomment-1109723415
This is probably a problem with the training data.
