### ISSUE TITLE
Some py files are not in the folder

### ISSUE THREAD

**Issue by keh-cv** [Alioth2000/RASVSR#3]
In this line of code, the vgg_arch file from basicsr.archs.vgg_arch import VGGFeatureExtractor does not have

**Comment by Alioth2000** [comment]
Since VGGFeatureExtractor is not used in this project, the file has been removed by me. If you want to use VGGFeatureExtractor, you can visit BasciSR's original project address: https://github.com/XPixelGroup/BasicSR/tree/master/basicsr/archs

**Comment by keh-cv** [comment]
Thank you very much for your reply, the problem has been solved temporarily.




st、
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alioth2000/RASVSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月27日(星期三) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alioth2000/RASVSR] Some py files are not in the folder (Issue #3)





 
Since VGGFeatureExtractor is not used in this project, the file has been removed by me. If you want to use VGGFeatureExtractor, you can visit BasciSR's original project address: https://github.com/XPixelGroup/BasicSR/tree/master/basicsr/archs
